[[LibTracyClient]]
arch = "aarch64"
git-tree-sha1 = "6686170f6945ceb8f9a7036c7ecc62221f7d3a7e"
os = "macos"

    [[LibTracyClient.download]]
    sha256 = "9cdcda05ee78fd95e16b2afa41c9f92165eee39ec3de9c740dd2784565fddcb1"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.aarch64-apple-darwin.tar.gz"
[[LibTracyClient]]
arch = "aarch64"
git-tree-sha1 = "07e93e030c06f7b8b07de262ddfda512a38a1283"
libc = "glibc"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "3c7cd2f1a607aadb5f59bd38fefa3dcd43ab93beb5580572ec8b65f695643387"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.aarch64-linux-gnu.tar.gz"
[[LibTracyClient]]
arch = "aarch64"
git-tree-sha1 = "d308363a55837fd16556e6879b65c128d41d5b6b"
libc = "musl"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "dfce177cc014dd061ab29a48566f8e93832d3c4d5f4a451858e0193c7ca2c54d"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.aarch64-linux-musl.tar.gz"
[[LibTracyClient]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b652caeea3d6af2d13041ffce9e3d4c7464b53b8"
libc = "glibc"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "5e17db69adab413571b00ba653d1c1e8dbf21b8aaf15ef8e9bc32acaac282b3a"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.armv6l-linux-gnueabihf.tar.gz"
[[LibTracyClient]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76bba5953dcf35fa93f0b296ca932435125dd225"
libc = "musl"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "559ddb52ee29228ce0965a1d078d5f6504acf42e64d78f6a5bf1624d5fd4648a"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.armv6l-linux-musleabihf.tar.gz"
[[LibTracyClient]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bdb28296bd4b86cce64cb668aabd95721601fc7a"
libc = "glibc"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "443e29025e65cbdc973c5bbbcbe6130e8519628aa4d93872f9d22d39e860131d"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.armv7l-linux-gnueabihf.tar.gz"
[[LibTracyClient]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5cb7dfa33f1b82161af989af477a24209cc6082b"
libc = "musl"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "1f0080009e2098f74c0b91b02778526858fc3a3ddc1ee8d2c3bd7908c6575f60"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.armv7l-linux-musleabihf.tar.gz"
[[LibTracyClient]]
arch = "i686"
git-tree-sha1 = "1ff3cd63a35c92b5e8d473dc665f37a5a2e53489"
libc = "glibc"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "3bfcdd88a1936af530d95517cfff56fa4b5688a19b1df1605f8f29320d869b5d"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.i686-linux-gnu.tar.gz"
[[LibTracyClient]]
arch = "i686"
git-tree-sha1 = "ef9e007915fdbe779234e7583c37019f6dda8717"
libc = "musl"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "ba3700872230789f9da41544c116c4d5ab7d63a32d70b7077ee17945c632727c"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.i686-linux-musl.tar.gz"
[[LibTracyClient]]
arch = "i686"
git-tree-sha1 = "a893a3700a523c2db3390cd19106d07540dea389"
os = "windows"

    [[LibTracyClient.download]]
    sha256 = "409db198fe24be7003071fbfa82a0c5fffe74082dc962073103415e55c9aba36"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.i686-w64-mingw32.tar.gz"
[[LibTracyClient]]
arch = "powerpc64le"
git-tree-sha1 = "79da94b37f8fd989afa829f2b66a7598e86f029f"
libc = "glibc"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "09a95e593e82d652e98f2ff0920cddd3772ce9ef6e00e6312aca182f5ef01160"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.powerpc64le-linux-gnu.tar.gz"
[[LibTracyClient]]
arch = "x86_64"
git-tree-sha1 = "72ce4b5fddf095251e119ced91e5a1a904ed6fdf"
os = "macos"

    [[LibTracyClient.download]]
    sha256 = "13258cfadde8c8395b33a6f608c91acb3aba89b2dd06ef6e3109ae48faac23c4"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.x86_64-apple-darwin.tar.gz"
[[LibTracyClient]]
arch = "x86_64"
git-tree-sha1 = "c3a19220a31475e9c535638be919a23f1b89c965"
libc = "glibc"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "deea0b8195b7efc958503e02767a9d13e25ea8a22491c36ef25eeeb13cbe268e"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.x86_64-linux-gnu.tar.gz"
[[LibTracyClient]]
arch = "x86_64"
git-tree-sha1 = "a2fec3663f6ffe664f801ef91d6f8b029cd69ec9"
libc = "musl"
os = "linux"

    [[LibTracyClient.download]]
    sha256 = "a9f20d02ea9f40d8be6a82831912e7f2f7d759995273c1f2822152beb7be7d2e"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.x86_64-linux-musl.tar.gz"
[[LibTracyClient]]
arch = "x86_64"
git-tree-sha1 = "c0eb1ab5b5162be2991eff730160e028623d4e5c"
os = "freebsd"

    [[LibTracyClient.download]]
    sha256 = "dbb8100626285284ebccbc4bb0a47201e6b2424dafe1da98e5ee3f4180cf9c80"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.x86_64-unknown-freebsd.tar.gz"
[[LibTracyClient]]
arch = "x86_64"
git-tree-sha1 = "4324905bea2b024a8f4947a53113a66b8fb994e5"
os = "windows"

    [[LibTracyClient.download]]
    sha256 = "f522f546f9b97846aab45d6e5e1e9b50be23d8f42a64484be14fdac2fa736fb1"
    url = "https://github.com/JuliaBinaryWrappers/LibTracyClient_jll.jl/releases/download/LibTracyClient-v0.9.1+0/LibTracyClient.v0.9.1.x86_64-w64-mingw32.tar.gz"
